default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db


development:
  <<: *default
  database: webapp_development
  username: root
  password: <%= ENV.fetch('MYSQL_ROOT_PASSWORD', 'db_root_password') %>

test:
  <<: *default
  database: webapp_test
  username: root
  password: <%= ENV.fetch('MYSQL_ROOT_PASSWORD', 'db_root_password') %>

production:
  <<: *default
  database: portfolio-db-instance
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: portfolio-db-instance.cflfus51yaox.ap-northeast-1.rds.amazonaws.com
  username: root
  password: 31415masarumosu
