default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>

development:
  <<: *default
  host: db
  database: webapp_development

test:
  <<: *default
  database: webapp_test
  host: db
  
production:
  <<: *default
  database: portfolio_production
  password: 31415masarumosuX@
  host: localhost
